---
title: "AmazonReviews"
author: "Kevin Kraayeveld (589908)"
date: "2024-03-13"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# List of required packages
packages <- c("data.table", "parallel")

# Check if each package is installed, if not, install it
for (package in packages) {
  if (!requireNamespace(package, quietly = TRUE)) {
    install.packages(package)
  }
}

library(data.table)
library(parallel)

num_cores <- detectCores()

setDTthreads(threads = num_cores)

readRenviron("../.env")
python_path <- Sys.getenv("PYTHON_PATH")
```

```{r config, echo = FALSE, warning = FALSE}
get_new_data <- T

# Choose preprocessing method
# - "complete_cleaning"
# - "no_stemming"
# - "minimal_cleaning" BROKEN: writes data wrong

preprocessing_method <- "no_stemming"

small_data <- T

# Choose embedding model. The choices are:
# - "word2vec_cbow"
# - "word2vec_skipgram"
# - "GloVe"
# - "fastText"
# - "BERT"
# - "ELMO" BROKEN: tensorflow error
# - "pretrained_word2vec"
# - "pretrained_glove"
# - "pretrained_fasttext"
# - "Lexicon"
embedding_model <- "pretrained_word2vec"
# If you want to run the embeddings file to get new embeddings this is TRUE. 
# This has to be True for pretrained models
get_new_embeddings <- T

create_new_vectors <- T
# Choose vectorization method
# - average
# - stacked
# - add
vectorization_method <- "average"

# Choose prediction model. The choices are:
# - "logistic_regression"
# - "ridge_regression"
prediction_model <- "logistic_regression"
# If you want to run the prediction file to get new predictions this is TRUE. 
# If you have the predictions saved in an Rds file then this is FALSE.
get_new_predictions <- TRUE
```

```{r process, include = FALSE}
if(tolower(embedding_model) %in% c("elmo", "bert", "lexicon")){
  run_vectorization <- F
} else{
  run_vectorization <- T
}

if(tolower(embedding_model) == "lexicon"){
  run_prediction <- F
} else{
  run_prediction <- T
}

if(tolower(embedding_model) %in% c("word2vec_cbow", "word2vec_skipgram", "glove", "pretrained_word2vec", "pretrained_glove")){
  test_oov <- T
} else{
  test_oov <- F
}

if(tolower(embedding_model) %in% c("pretrained_word2vec", "pretrained_glove")){
  train_oov <- T
} else{
  train_oov <- F
}

```

## Data preprocessing

```{r read_cleaned_data, echo = FALSE, warning = FALSE}
if(get_new_data){
  path <- paste0("Preprocessing/", preprocessing_method, ".R")
  source(path)
} else if(!get_new_data & (get_new_predictions | create_new_vectors)){
  if(small_data){
    file_path_train <- paste0("../data/Cleaned-Reviews/", preprocessing_method, "_train_small.csv")
    train <- fread(file_path_train)
    file_path_test <- paste0("../data/Cleaned-Reviews/", preprocessing_method, "_test_small.csv")
    test <- fread(file_path_test)
  } else{
    file_path_train <- paste0("../data/Cleaned-Reviews/", preprocessing_method, "_train.csv")
    train <- fread(file_path_train)
    file_path_test <- paste0("../data/Cleaned-Reviews/", preprocessing_method, "_test.csv")
    test <- fread(file_path_test)
  }
  # Splitting the Tokens column into a list of characters
  train$Review_Tokens <- strsplit(train$Review_Tokens, "\\|")
  test$Review_Tokens <- strsplit(test$Review_Tokens, "\\|")
}
```

## Embedding model

```{r embedding_model, echo = FALSE, warning = FALSE, include = FALSE}
if(get_new_embeddings){
  file_name <- paste0(embedding_model, ".R")
  path <- paste0("Embedding-Models/", file_name)
  source(path)
  if(small_data){
    model_path <- paste0("../data/Models/", embedding_model, "_small.rds")
  } else{
    model_path <- paste0("../data/Models/", embedding_model, ".rds")
  }
} else{
  if(small_data){
    file_name <- paste0(embedding_model, "_small.rds")
  } else{
    file_name <- paste0(embedding_model, ".rds")
  }
  path <- paste0("../data/Models/", file_name)
  model <- readRDS(path)
}
```

## Review vectorization

```{r review_vectorization, echo = FALSE, warning = FALSE}
if(run_vectorization){
  if(create_new_vectors){
    if(test_oov){
      if(small_data){
        test_path <- paste0("../data/Cleaned-Reviews/", preprocessing_method, "_test_small_no_oov.csv")
      } else{
        test_path <- paste0("../data/Cleaned-Reviews/", preprocessing_method, "_test_no_oov.csv")
      }
      test <- fread(test_path)
      test$Review_Tokens <- strsplit(test$Review_Tokens, "\\|")
    }
    if(train_oov){
      if(small_data){
        train_path <- paste0("../data/Cleaned-Reviews/", preprocessing_method, "_train_small_no_oov.csv")
      } else{
        train_path <- paste0("../data/Cleaned-Reviews/", preprocessing_method, "_train_no_oov.csv")
      }
      train <- fread(train_path)
      train$Review_Tokens <- strsplit(train$Review_Tokens, "\\|")
    }
    file_name <- paste0(vectorization_method, "_vectorization.R")
    path <- paste0("Review-Vectorization/", file_name)
    source(path)
    if(small_data){
      path2 <- paste0("../data/Vectorized-Reviews/", vectorization_method,"_", embedding_model, "_train_small.csv")
      path3 <- paste0("../data/Vectorized-Reviews/", vectorization_method,"_", embedding_model, "_test_small.csv")
    }else{
      path2 <- paste0("../data/Vectorized-Reviews/", vectorization_method,"_", embedding_model, "_train.csv")
      path3 <- paste0("../data/Vectorized-Reviews/", vectorization_method,"_", embedding_model, "_test.csv")
    }
    fwrite(train, path2)
    fwrite(test, path3)
    } else{
      if(small_data){
        file_name <- paste0(vectorization_method, "_", embedding_model, "_train_small.csv")
        file_name2 <- paste0(vectorization_method, "_", embedding_model, "_test_small.csv")
      }else{
        file_name <- paste0(vectorization_method, "_", embedding_model, "_train.csv")
        file_name2 <- paste0(vectorization_method, "_", embedding_model, "_test.csv")
      }
    path <- paste0("../data/Vectorized-Reviews/", file_name)
    train <- fread(path)
    train$Review_Vector <- strsplit(train$Review_Vector, "\\|")
    train$Review_Vector <- lapply(train$Review_Vector, function(x) as.numeric(x))
    path2 <- paste0("../data/Vectorized-Reviews/", file_name2)
    test <- fread(path2)
    test$Review_Vector <- strsplit(test$Review_Vector, "\\|")
    test$Review_Vector <- lapply(test$Review_Vector, function(x) as.numeric(x))
    }
}
```

## Prediction model

```{r prediction_model, echo = FALSE, warning = FALSE}
if(run_prediction){
  if(get_new_predictions){
    file_name <- paste0(prediction_model, ".R")
    path <- paste0("Prediction-Models/", file_name)
    source(path)
  } else{
    file_name <- paste0(prediction_model, ".Rdata")
    path <- paste0("Prediction-Models/", file_name)
    load(path)
  }
}
```

## Evaluation

```{r evaluation, echo = FALSE, warning = FALSE}
source("Evaluation/Evaluation.R")
```